### ISSUE TITLE
"return" or "?" in the decorated function is cancelling the retry mechanism

### ISSUE THREAD

**Issue by haxorcize** [Brendan-Blanchard/retry-if#3]
If the decorated function uses `return` anywhere, or even using the `?` operator with `let something = some_api_that_can_fail()?;` , it'll cancel out the retry mechanism.

When the macro expands, and `#block` gets replaced with the decorated function's code. The `return` or `?` will cause the code to return from the macro-generated function without continuing in the retry loop or even calling the `#retry_if` function.

This sample code:

```rust
fn retry_if(result: &Result<()>) -> bool {
    result.is_err()
}

#[retry(BACKOFF_CONFIG, retry_if)]
async fn some_async_method() -> Result<()> {
    bail!("Test");
}
```

Will transform into:

```rust
async fn some_async_method() -> Result<()> {
    let start = tokio::time::Instant::now();
    let backoff_max = BACKOFF_CONFIG.backoff_max.unwrap_or(std::time::Duration::MAX);
    let mut attempt = 0;
    loop {
        let result = {
            return ::anyhow::__private::Err({
                let error = ::anyhow::__private::format_err(format_args!("Test"));
                error
            });
        };
        // THIS POINT ON WILL NOT GET EXECUTED....
        if !retry_if(&result) || attempt >= BACKOFF_CONFIG.max_retries {
            return result;
        }
        attempt += 1;
        ...
```

Same with this code:

```rust
fn some_api_that_can_fail() -> Result<String> {
    Err(anyhow!("I failed..."))
}

#[retry(BACKOFF_CONFIG, retry_if)]
async fn some_async_method() -> Result<()> {

    let something = some_api_that_can_fail()?;
    info!("I got something: {something}");

    Ok(())
}
```

Will not have any retries.

**Comment by haxorcize** [comment]
Found a way to make this work. Inside `decorate_fn` we wrap the `#block` with a named block:
```rust
                let result = 'block: {
                    #block
                };
```

And then I use syn::visit_mut to modify `impl_fn.block` (aka `#block`) such that:

```rust
something()?
```

will turn into

```rust
match something() {
    Ok(val) => val,
    Err(err) => break 'block Err(err),
}
```

and

```rust
return something
```

will turn into

```rust
break 'block something
```

I'm testing locally to see if this works well. Happy to open a pull request later on

**Comment by haxorcize** [comment]
Ok I opened a PR here: https://github.com/Brendan-Blanchard/retry-if/pull/4
Did some anecdotal testing with decorating functions with `?` and `return` in them (or return as a result of macros like `bail!(...)`) and it works nicely. Would love feedback on the approach of modifying the block + need proper unit testing, docs.

**Comment by Brendan-Blanchard** [comment]
Thanks for finding and looking into this! I didn't know about `VisitMut` for modifying while parsing the tree. I wonder if longer term there will be another few cases that need addressing this way, but this looks good to me. I think the most permanent solution would be to completely separate the code into a new function, but that would require getting the idents for all args, etc and passing in just like a real decorator in another language would work. I can try to break this implementation with tests this evening, and if all looks good we can get it merged and cut a release from it. Thanks again!

**Comment by haxorcize** [comment]
Yeah, once you start trying to call the decorated function as a standalone function, that'll take all the `return` and `?` issues away (and any future issues), but it'll drive you into ownership hell, which will very quickly look like `backon` and other libraries.

Specifically look at their "Retry functions with receiver &mut self." in [here](https://docs.rs/backon/latest/backon/) - it became so convoluted to use where you have the pass the parameters into the context, and then also have your decorated async block keep returning back the parameters. I tried really hard making it work but it was so ugly I didn't want to commit it and scare my co-workers :) 

That's what's brilliant about your crate. It's simple, and it works just like you would if you were implementing a retry loop yourself in your function. I'm sure we'll run into more issues though :)

BTW if you wanna be fancy you can also feature-gate that block modification functionality, although I'd argue it's not very usable if you try to decorate functions that use `?` or `return`, so maybe it should be enabled by default

**Comment by Brendan-Blanchard** [comment]
I wondering if it's possible in a macro implementation, but maybe it's a different kind of complicated?

I don't see an initial reason that it wouldn't be possible to expand something like the below, with the main caveat being the difficulty I'm sure there would be around detecting `self` and fixing the `can't use 'Self' from outer item` you'd see if not somehow getting `this: &mut TestStruct` in there instead of `this: &mut Self`:

```
pub struct TestStruct {
    out: Box<dyn Write>, // just so I'm actually using &mut self
}

impl TestStruct {
    pub async fn pretend_this_was_expanded(&mut self, output: &str) -> std::io::Result<usize> {
        async fn pretend_this_was_the_original(this: &mut TestStruct, output: &str) -> std::io::Result<usize> {
            this.out.write(output.as_bytes())
        }

        let mut count = 0;

        loop {
            let _ = pretend_this_was_the_original(self, output).await;
            if count >= 1 {
                // convince compiler this will exit, and show multiple calls are okay
                break;
            }
        }

        pretend_this_was_the_original(self, output).await
    }
}
```

I might explore that more this weekend if I get the time. For now I'll follow up in your PR from my initial testing.

**Comment by haxorcize** [comment]
Thx Brendan, I'm traveling this week but will check your test and response above towards EOW.

In the meanwhile I found and fixed a small bug that I wanted to share with you:

Look at this function:
```rust
#[retry(...)]
async fn foo() -> anyhow::Result<String> {
    let json_string = serde_json::from_string("\"json string\"")?;
    Ok(json_string);
}
```

Normally this would compile fine, even though the try operator on `from_string` is actually returning `serde_json::Error`, while the function's result expects `anyhow::Error` - but it works since `anyhow::Error` implemented `From<E> where E: std::error::Error`.

But when we decorate this code into the retry code, and this try operator will look like:
```rust
... // retry loop
let result = 'block: {
    let json_string = match serde_json::from_string("\"json string\"") {
        Ok(val) => val,
        Err(err) => break 'block Err(err),
    }
    ...
}
... // rest of retry loop
```


Then it will try to return `Err(serde_json::Error(...))` which would not get magically converted into the expected error type, and would break compilation. I'm curious if you know why it works in a function return type, but not if you try it inside a block.

Anyway, the fix was easy, I changed the `BlockModifier` code that modifies the try operator to use `err.into()`:
```rust
            *i = Expr::Match(parse_quote! {
                match #expr {
                    Ok(val) => val,
                    Err(err) => break 'block Err(err.into()),
                }
            });
```

And it works great now.

It'll still fail compiling if into() can't be done (if `From<E>` wasn't implemented for example), and it'll do nothing if you're converting one error to itself.

**Comment by haxorcize** [comment]
> I wondering if it's possible in a macro implementation, but maybe it's a different kind of complicated?
> 
> I don't see an initial reason that it wouldn't be possible to expand something like the below, with the main caveat being the difficulty I'm sure there would be around detecting `self` and fixing the `can't use 'Self' from outer item` you'd see if not somehow getting `this: &mut TestStruct` in there instead of `this: &mut Self`:
> 
> ```
> pub struct TestStruct {
>     out: Box<dyn Write>, // just so I'm actually using &mut self
> }
> 
> impl TestStruct {
>     pub async fn pretend_this_was_expanded(&mut self, output: &str) -> std::io::Result<usize> {
>         async fn pretend_this_was_the_original(this: &mut TestStruct, output: &str) -> std::io::Result<usize> {
>             this.out.write(output.as_bytes())
>         }
> 
>         let mut count = 0;
> 
>         loop {
>             let _ = pretend_this_was_the_original(self, output).await;
>             if count >= 1 {
>                 // convince compiler this will exit, and show multiple calls are okay
>                 break;
>             }
>         }
> 
>         pretend_this_was_the_original(self, output).await
>     }
> }
> ```
> 
> I might explore that more this weekend if I get the time. For now I'll follow up in your PR from my initial testing.

If it works well - it would be ideal since this is way cleaner. But like a lot of things with Rust - what might look like a great idea could end up in a compilation nightmare 🤣 

One area I'd check is something like this:

```rust
#[retry...]
async fn wrapped(foo: T) -> Result<()> {
    // do something that might fail
}
```

then in the expanded version above it'll become an issue since foo will transfer and won't be able to be called in a loop:

```rust
async fn wrapper(foo: T) -> Result<()> {
    async fn wrapped(foo: T) -> Result<()> {
        //do something that might fail
    }

    loop {
        let result = wrapped(foo).await?;
        // decide if to retry
    }
}
```

Wouldn't `foo` just move inside wrapped once and you won't be able to call it again?

**Comment by Brendan-Blanchard** [comment]
I'm definitely getting more and more familiar with the "once great" ideas that eat a few hours or days before finding an idiomatic way in Rust.

For the ownership/consuming functions, I think that's unavoidable even with the current implementation? It's something I called out in the readme about impl functions that consume `self`, and I added a UI failure test for it in your PR that I just merged. Even without a wrapper function, if the block of code uses an owned value in a way that it really needs ownership, you can't run it twice since whatever it is could truly be gone (i.e. you destroyed the value by sending it over a channel, dropping it, etc.). 

Now that I've cut a release with your fixes, I'm going to close this. Let me know if you come across anything else in the new release (v0.2.0). If I get the time to try a full wrapper version I'll loop you in, thanks again for your help in finding and fixing this!
